services:
  mongo:
    image: mirror.gcr.io/library/mongo:8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: web3
    ports:
      - "27017:27017"
    networks:
      - desarrolloweb3_mongo-network

  calculadora:
    image: ghcr.io/scarkat/web-3/backend:main
    volumes:
      - ./backend:/app
    ports:
      - "8089:8000"
    networks:
      - desarrolloweb3_mongo-network

  frontend:
    image: ghcr.io/scarkat/web-3-frontend:v1.0.1
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - calculadora
    networks:
      - desarrolloweb3_mongo-network

networks:
  desarrolloweb3_mongo-network:
    driver: bridge